portfolio:
  stocks:
    - TSLA
    - NVDA
    - PAYO
  etfs:
    - SPY
    - VOO
  crypto:
    - bitcoin
watchlist:
  stocks:
    - ATAI
    - CPRT
  crypto:
    - cardano
    - xrp
    - sui
    - ethereum
    - solana
