portfolio:
  stocks:
    - TSLA
    - NVDA
    - PAYO
  etfs:
    - SPY
    - VOO
  crypto:
    - bitcoin
    - ripple
    - sui
    - ethereum
    - solana
watchlist:
  stocks:
    - ATAI
    - CPRT
  crypto:
    - cardano
